entrypoint = "run_hr_dashboard.py"

[patterns]
include = ["hrdash/**/*.py", "streamlit_app.py", "run_hr_dashboard.py", "template_cuti_karyawan.xlsx"]
exclude = ["**/__pycache__/**", ".git/**", ".venv/**"]

[options]
debug = false
extract_to_temp = false
delete_after_run = false
run_quietly = false
offline_mode = false
uv_version = "0.9.21"
